@WebMinimalApi_Salmple_HostAddress = http://localhost:5240

Post {{WebMinimalApi_Salmple_HostAddress}}/SampleGroup/weatherforecast?id2=2 
Content-Type: application/x-www-form-urlencoded
Accept: application/json, text/plain, */*
  id=1102
###

Post {{WebMinimalApi_Salmple_HostAddress}}/SampleGroup/weatherforecast?id2=22
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryy1AbSLBrpdJdg4Ah
Accept: application/json, text/plain, */*
#X-Requested-With: XMLHttpRequest
 ------WebKitFormBoundaryy1AbSLBrpdJdg4Ah
Content-Disposition: form-data; name="Test[Id]"

9311025267
------WebKitFormBoundaryy1AbSLBrpdJdg4Ah--

###

Post {{WebMinimalApi_Salmple_HostAddress}}/SampleGroup/weatherforecast/
Content-Type: application/json
Accept: application/json, text/plain, */*

{
  "id": 11000
}
###


Post {{WebMinimalApi_Salmple_HostAddress}}/SampleGroup/weatherforecast?id=555
Accept: application/json, text/plain, */*

###
